### ISSUE TITLE
v9.0.6 / v9.0.7 build error - Type 'GraphQLScalarType' is not generic

### ISSUE THREAD

**Issue by arimus** [graphql-compose/graphql-compose#374]
Noticed this error when updated to either 9.0.6 or 9.0.7 from 9.0.4. This build error is ocurring:

    node_modules/graphql-compose/lib/type/buffer.d.ts(3,25): error TS2315: Type 'GraphQLScalarType' is not generic.

9.0.4 works fine though. Using graphql version 15.8.0.

**Comment by wkillerud** [comment]
The generics were only added in `graphql@16.0.0` from what I can tell. They should not be used while `^14.2.0` and `^15.0.0` are in `peerDependencies`.

Introduced in https://github.com/graphql-compose/graphql-compose/commit/48a3566340b492012fcc6a0569a62a0149f70a7d by the looks of it.

**Comment by tony** [comment]
This is a breaking change for `tsc`, This is the kind of change we'd want in a major release, ideally with a deprecation warning

@nodkz Is 9.x intended to drop support for graphql versions under 16?

**Comment by disintegrator** [comment]
For what it's worth, gatsby is currently tied to `graphql@^15` and `graphql-compose@^9.0.6`.
