### ISSUE TITLE
TypeMapper not work with graphql 0.12+

### ISSUE THREAD

**Issue by luyanfei** [graphql-compose/graphql-compose#106]
I try to define type with TypeMapper like this:
`const UserLoginPayload = TypeMapper.createType("type UserLoginPayload { username: String!, email: String!}")
`
When run the code, I always get error message:
`
./node_modules/graphql-compose/lib/typeMapper.js:657
    description: (0, _buildASTSchema.getDescription)(def),
                                                    ^

TypeError: (0 , _buildASTSchema.getDescription) is not a function
    at makeTypeDef (/opt/sources/weitalk-backend/node_modules/graphql-compose/lib/typeMapper.js:657:53)
    at makeSchemaDef (/opt/sources/weitalk-backend/node_modules/graphql-compose/lib/typeMapper.js:534:14)
    at parseTypes (/opt/sources/weitalk-backend/node_modules/graphql-compose/lib/typeMapper.js:500:16)
    at TypeMapper.createType (/opt/sources/weitalk-backend/node_modules/graphql-compose/lib/typeMapper.js:150:19)
    at Object.<anonymous> (/opt/sources/weitalk-backend/src/schemas/user.js:15:37)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at __dirname.forEach.file (/opt/sources/weitalk-backend/src/schemas/index.js:6:41)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/opt/sources/weitalk-backend/src/schemas/index.js:5:49)
    at Module._compile (module.js:643:30)
`
After change graph-js to 0.11.7, problem is resolved.

**Comment by nodkz** [comment]
Thanks for reporting.
Waiting a new graphql-js version from @leebyron
Proper changes already merged with its master.
With upcoming 0.12.4 it should work.

**Comment by nodkz** [comment]
2 days ago was published `graphql@0.13.0-rc.1`, you may install `graphql-compose@2.13.1` which works with them.

**Comment by luyanfei** [comment]
Thanks for hard work.
